name: Python CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Step 1 - Get code
        uses: actions/checkout@v3

      - name: Step 2 - Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Step 3 - Install dependencies
        run: pip install -r requirements.txt

      - name: Step 4 - Run Python script
        run: python app.py
